version: '3'

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    image: elifesciences/data-science-peertax-runner:${IMAGE_TAG}
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: elifesciences/data-science-peertax-jupyter:${IMAGE_TAG}
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "${PEERTAX_JUPYTER_PORT}:8888"
